name: Flutter Web Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze lib
        run: flutter analyze lib

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: KurdDesign-AI-Web
          path: build/web
          if-no-files-found: error
