name: Flutter iOS Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create iOS platform
        run: flutter create . --platforms ios

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze lib
        run: flutter analyze lib

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create iOS app archive
        run: |
          cd build/ios/iphoneos
          zip -r KurdDesign-AI-iOS.zip Runner.app

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: KurdDesign-AI-iOS
          path: build/ios/iphoneos/KurdDesign-AI-iOS.zip
          if-no-files-found: error
